[package]
name = "tarpc"
version = "0.6.0"
authors = ["Adam Wright <adam.austin.wright@gmail.com>", "Tim Kuehn <timothy.j.kuehn@gmail.com>"]
license = "MIT"
documentation = "https://docs.rs/tarpc"
homepage = "https://github.com/google/tarpc"
repository = "https://github.com/google/tarpc"
keywords = ["rpc", "protocol", "remote", "procedure", "serialize"]
readme = "README.md"
description = "An RPC framework for Rust with a focus on ease of use."

[dependencies]
bincode = "0.6"
byteorder = "0.5"
bytes = { git = "https://github.com/carllerche/bytes" }
futures = { git = "https://github.com/alexcrichton/futures-rs" }
lazy_static = "0.2"
log = "0.3"
scoped-pool = "1.0"
serde = "0.8"
serde_derive = "0.8"
tarpc-plugins = { path = "src/plugins" }
take = "0.1"
tokio-service = { git = "https://github.com/tokio-rs/tokio-service" }
tokio-proto = { git = "https://github.com/tokio-rs/tokio-proto" }
tokio-core = { git = "https://github.com/tokio-rs/tokio-core" }
net2 = "0.2"

[replace]
"tokio-core:0.1.2" = { git = "https://github.com/tokio-rs/tokio-core" }
"futures:0.1.7" = { git = "https://github.com/alexcrichton/futures-rs" }

[dev-dependencies]
chrono = "0.2"
env_logger = "0.3"
futures-cpupool = "0.1"
clap = "2.0"

[features]
unstable = ["serde/unstable"]

[workspace]
