cargo-features = ["rename-dependency"]

[package]
name = "tarpc-lib"
version = "0.2.0"
authors = ["Tim Kuehn <tikue@google.com>"]
edition = '2018'
license = "MIT"
documentation = "https://docs.rs/tarpc-lib"
homepage = "https://github.com/google/tarpc"
repository = "https://github.com/google/tarpc"
keywords = ["rpc", "network", "server", "api", "microservices"]
categories = ["asynchronous", "network-programming"]
readme = "../README.md"
description = "An RPC framework for Rust with a focus on ease of use."

[features]
default = []
serde1 = ["trace/serde", "serde", "serde/derive"]

[dependencies]
fnv = "1.0"
humantime = "1.0"
log = "0.4"
pin-utils = "0.1.0-alpha.3"
rand = "0.5"
tokio-timer = "0.2"
trace = { package = "tarpc-trace", version = "0.1", path = "../trace" }
serde = { optional = true, version = "1.0" }

[target.'cfg(not(test))'.dependencies]
futures-preview = { version = "0.3.0-alpha.9", features = ["compat"] }

[dev-dependencies]
futures-preview = { version = "0.3.0-alpha.9", features = ["compat", "tokio-compat"] }
futures-test-preview = { version = "0.3.0-alpha.9" }
env_logger = "0.5"
tokio = "0.1"
