[package]
name = "tarpc"
version = "0.5.0"
authors = ["Adam Wright <adam.austin.wright@gmail.com>", "Tim Kuehn <timothy.j.kuehn@gmail.com>"]
license = "MIT"
documentation = "https://google.github.io/tarpc"
homepage = "https://github.com/google/tarpc"
repository = "https://github.com/google/tarpc"
keywords = ["rpc", "protocol", "remote", "procedure", "serialize"]
readme = "../README.md"
description = "An RPC framework for Rust with a focus on ease of use."

[dependencies]
bincode = "0.5"
log = "0.3"
scoped-pool = "0.1"
serde = "0.7"
unix_socket = "0.5"

[dev-dependencies]
lazy_static = "0.1"
env_logger = "0.3"
tempdir = "0.3"
